version: '3'
services:
  postgresql:
    image: postgres:13
    container_name: postgresqldb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test@123
      POSTGRES_DB: catalog


